import { Inter } from "next/font/google";
import "./globals.scss";
import { ApolloWrapper } from "../lib/apollowrapper";
import Notification from "../components/common/Notifications";
import StoreProvider from "@/lib/StoreProvider";
import { AuthProvider } from "@/lib/AuthProvider";
// import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SCL MGT SYS",
  description: "Generated by create next app, developed by Nadim Chowdhury",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
            <ApolloWrapper>{children}</ApolloWrapper>
            <Notification />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
